package com.fire.dao;

import com.fire.po.Checkrecord;
import com.fire.po.CheckrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckrecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int countByExample(CheckrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int deleteByExample(CheckrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int deleteByPrimaryKey(Integer recordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int insert(Checkrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int insertSelective(Checkrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	List<Checkrecord> selectByExample(CheckrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	Checkrecord selectByPrimaryKey(Integer recordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Checkrecord record,
			@Param("example") CheckrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int updateByExample(@Param("record") Checkrecord record,
			@Param("example") CheckrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int updateByPrimaryKeySelective(Checkrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table checkrecord
	 * 
	 * @mbggenerated Mon Oct 31 11:55:13 CST 2016
	 */
	int updateByPrimaryKey(Checkrecord record);
}