package com.fire.dao;

import com.fire.po.User;
import com.fire.po.UserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Aug 01 18:28:53 CST 2016
     */
    int updateByPrimaryKey(User record);
    
    //以下代码由用户自己添加
   	@Select("select * from user u where u.userid = #{userid}")
   	User getUserById(int userid);
   	@Select("select user.userid,user.username,user.password,user.relname,user.lastlogin,role.roleid,role.usertype from user left join role on user.roleid = role.roleid where role.roleid is not NULL")
   	List<User> listPageUser(User user);
   	@Select("select count(userid) from user where username = #{username}")
   	int getCountByName(String username);
   	//根据用户id得到用户权限
   	@Select("select u.userid,u.username,u.userlimit,u.relname,u.password,r.roleid,r.usertype,r.userlimit from user u left join role r on u.roleid=r.userlimit where u.userid = #{userid}")
   	User getUserAndRoleById(Integer userid);
   	@Select("select * from user where username = #{username} or tel = #{username} and password = #{password}")
   	User getUserInfo(@Param("username")String username, @Param("password")String password);
}