package com.fire.po;

import java.util.ArrayList;
import java.util.List;

public class CheckrecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public CheckrecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordidIsNull() {
            addCriterion("recordid is null");
            return (Criteria) this;
        }

        public Criteria andRecordidIsNotNull() {
            addCriterion("recordid is not null");
            return (Criteria) this;
        }

        public Criteria andRecordidEqualTo(Integer value) {
            addCriterion("recordid =", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotEqualTo(Integer value) {
            addCriterion("recordid <>", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThan(Integer value) {
            addCriterion("recordid >", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThanOrEqualTo(Integer value) {
            addCriterion("recordid >=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThan(Integer value) {
            addCriterion("recordid <", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThanOrEqualTo(Integer value) {
            addCriterion("recordid <=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidIn(List<Integer> values) {
            addCriterion("recordid in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotIn(List<Integer> values) {
            addCriterion("recordid not in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidBetween(Integer value1, Integer value2) {
            addCriterion("recordid between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotBetween(Integer value1, Integer value2) {
            addCriterion("recordid not between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNull() {
            addCriterion("unitid is null");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNotNull() {
            addCriterion("unitid is not null");
            return (Criteria) this;
        }

        public Criteria andUnitidEqualTo(Integer value) {
            addCriterion("unitid =", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotEqualTo(Integer value) {
            addCriterion("unitid <>", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThan(Integer value) {
            addCriterion("unitid >", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unitid >=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThan(Integer value) {
            addCriterion("unitid <", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThanOrEqualTo(Integer value) {
            addCriterion("unitid <=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidIn(List<Integer> values) {
            addCriterion("unitid in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotIn(List<Integer> values) {
            addCriterion("unitid not in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidBetween(Integer value1, Integer value2) {
            addCriterion("unitid between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotBetween(Integer value1, Integer value2) {
            addCriterion("unitid not between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNull() {
            addCriterion("unitname is null");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNotNull() {
            addCriterion("unitname is not null");
            return (Criteria) this;
        }

        public Criteria andUnitnameEqualTo(String value) {
            addCriterion("unitname =", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotEqualTo(String value) {
            addCriterion("unitname <>", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThan(String value) {
            addCriterion("unitname >", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThanOrEqualTo(String value) {
            addCriterion("unitname >=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThan(String value) {
            addCriterion("unitname <", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThanOrEqualTo(String value) {
            addCriterion("unitname <=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLike(String value) {
            addCriterion("unitname like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotLike(String value) {
            addCriterion("unitname not like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameIn(List<String> values) {
            addCriterion("unitname in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotIn(List<String> values) {
            addCriterion("unitname not in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameBetween(String value1, String value2) {
            addCriterion("unitname between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotBetween(String value1, String value2) {
            addCriterion("unitname not between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andMasterIsNull() {
            addCriterion("master is null");
            return (Criteria) this;
        }

        public Criteria andMasterIsNotNull() {
            addCriterion("master is not null");
            return (Criteria) this;
        }

        public Criteria andMasterEqualTo(String value) {
            addCriterion("master =", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterNotEqualTo(String value) {
            addCriterion("master <>", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterGreaterThan(String value) {
            addCriterion("master >", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterGreaterThanOrEqualTo(String value) {
            addCriterion("master >=", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterLessThan(String value) {
            addCriterion("master <", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterLessThanOrEqualTo(String value) {
            addCriterion("master <=", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterLike(String value) {
            addCriterion("master like", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterNotLike(String value) {
            addCriterion("master not like", value, "master");
            return (Criteria) this;
        }

        public Criteria andMasterIn(List<String> values) {
            addCriterion("master in", values, "master");
            return (Criteria) this;
        }

        public Criteria andMasterNotIn(List<String> values) {
            addCriterion("master not in", values, "master");
            return (Criteria) this;
        }

        public Criteria andMasterBetween(String value1, String value2) {
            addCriterion("master between", value1, value2, "master");
            return (Criteria) this;
        }

        public Criteria andMasterNotBetween(String value1, String value2) {
            addCriterion("master not between", value1, value2, "master");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNull() {
            addCriterion("telphone is null");
            return (Criteria) this;
        }

        public Criteria andTelphoneIsNotNull() {
            addCriterion("telphone is not null");
            return (Criteria) this;
        }

        public Criteria andTelphoneEqualTo(String value) {
            addCriterion("telphone =", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotEqualTo(String value) {
            addCriterion("telphone <>", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThan(String value) {
            addCriterion("telphone >", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("telphone >=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThan(String value) {
            addCriterion("telphone <", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLessThanOrEqualTo(String value) {
            addCriterion("telphone <=", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneLike(String value) {
            addCriterion("telphone like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotLike(String value) {
            addCriterion("telphone not like", value, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneIn(List<String> values) {
            addCriterion("telphone in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotIn(List<String> values) {
            addCriterion("telphone not in", values, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneBetween(String value1, String value2) {
            addCriterion("telphone between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andTelphoneNotBetween(String value1, String value2) {
            addCriterion("telphone not between", value1, value2, "telphone");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureIsNull() {
            addCriterion("buildingstructure is null");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureIsNotNull() {
            addCriterion("buildingstructure is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureEqualTo(String value) {
            addCriterion("buildingstructure =", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureNotEqualTo(String value) {
            addCriterion("buildingstructure <>", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureGreaterThan(String value) {
            addCriterion("buildingstructure >", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureGreaterThanOrEqualTo(String value) {
            addCriterion("buildingstructure >=", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureLessThan(String value) {
            addCriterion("buildingstructure <", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureLessThanOrEqualTo(String value) {
            addCriterion("buildingstructure <=", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureLike(String value) {
            addCriterion("buildingstructure like", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureNotLike(String value) {
            addCriterion("buildingstructure not like", value, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureIn(List<String> values) {
            addCriterion("buildingstructure in", values, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureNotIn(List<String> values) {
            addCriterion("buildingstructure not in", values, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureBetween(String value1, String value2) {
            addCriterion("buildingstructure between", value1, value2, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andBuildingstructureNotBetween(String value1, String value2) {
            addCriterion("buildingstructure not between", value1, value2, "buildingstructure");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Double value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Double value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Double value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Double value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Double value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Double> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Double> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Double value1, Double value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Double value1, Double value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNull() {
            addCriterion("floors is null");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNotNull() {
            addCriterion("floors is not null");
            return (Criteria) this;
        }

        public Criteria andFloorsEqualTo(String value) {
            addCriterion("floors =", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotEqualTo(String value) {
            addCriterion("floors <>", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThan(String value) {
            addCriterion("floors >", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThanOrEqualTo(String value) {
            addCriterion("floors >=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThan(String value) {
            addCriterion("floors <", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThanOrEqualTo(String value) {
            addCriterion("floors <=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLike(String value) {
            addCriterion("floors like", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotLike(String value) {
            addCriterion("floors not like", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsIn(List<String> values) {
            addCriterion("floors in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotIn(List<String> values) {
            addCriterion("floors not in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsBetween(String value1, String value2) {
            addCriterion("floors between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotBetween(String value1, String value2) {
            addCriterion("floors not between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andRoomsIsNull() {
            addCriterion("rooms is null");
            return (Criteria) this;
        }

        public Criteria andRoomsIsNotNull() {
            addCriterion("rooms is not null");
            return (Criteria) this;
        }

        public Criteria andRoomsEqualTo(Integer value) {
            addCriterion("rooms =", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsNotEqualTo(Integer value) {
            addCriterion("rooms <>", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsGreaterThan(Integer value) {
            addCriterion("rooms >", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsGreaterThanOrEqualTo(Integer value) {
            addCriterion("rooms >=", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsLessThan(Integer value) {
            addCriterion("rooms <", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsLessThanOrEqualTo(Integer value) {
            addCriterion("rooms <=", value, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsIn(List<Integer> values) {
            addCriterion("rooms in", values, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsNotIn(List<Integer> values) {
            addCriterion("rooms not in", values, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsBetween(Integer value1, Integer value2) {
            addCriterion("rooms between", value1, value2, "rooms");
            return (Criteria) this;
        }

        public Criteria andRoomsNotBetween(Integer value1, Integer value2) {
            addCriterion("rooms not between", value1, value2, "rooms");
            return (Criteria) this;
        }

        public Criteria andBedIsNull() {
            addCriterion("bed is null");
            return (Criteria) this;
        }

        public Criteria andBedIsNotNull() {
            addCriterion("bed is not null");
            return (Criteria) this;
        }

        public Criteria andBedEqualTo(Integer value) {
            addCriterion("bed =", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedNotEqualTo(Integer value) {
            addCriterion("bed <>", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedGreaterThan(Integer value) {
            addCriterion("bed >", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedGreaterThanOrEqualTo(Integer value) {
            addCriterion("bed >=", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedLessThan(Integer value) {
            addCriterion("bed <", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedLessThanOrEqualTo(Integer value) {
            addCriterion("bed <=", value, "bed");
            return (Criteria) this;
        }

        public Criteria andBedIn(List<Integer> values) {
            addCriterion("bed in", values, "bed");
            return (Criteria) this;
        }

        public Criteria andBedNotIn(List<Integer> values) {
            addCriterion("bed not in", values, "bed");
            return (Criteria) this;
        }

        public Criteria andBedBetween(Integer value1, Integer value2) {
            addCriterion("bed between", value1, value2, "bed");
            return (Criteria) this;
        }

        public Criteria andBedNotBetween(Integer value1, Integer value2) {
            addCriterion("bed not between", value1, value2, "bed");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemIsNull() {
            addCriterion("securitysystem is null");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemIsNotNull() {
            addCriterion("securitysystem is not null");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemEqualTo(Integer value) {
            addCriterion("securitysystem =", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemNotEqualTo(Integer value) {
            addCriterion("securitysystem <>", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemGreaterThan(Integer value) {
            addCriterion("securitysystem >", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemGreaterThanOrEqualTo(Integer value) {
            addCriterion("securitysystem >=", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemLessThan(Integer value) {
            addCriterion("securitysystem <", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemLessThanOrEqualTo(Integer value) {
            addCriterion("securitysystem <=", value, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemIn(List<Integer> values) {
            addCriterion("securitysystem in", values, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemNotIn(List<Integer> values) {
            addCriterion("securitysystem not in", values, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemBetween(Integer value1, Integer value2) {
            addCriterion("securitysystem between", value1, value2, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andSecuritysystemNotBetween(Integer value1, Integer value2) {
            addCriterion("securitysystem not between", value1, value2, "securitysystem");
            return (Criteria) this;
        }

        public Criteria andTransportationplanIsNull() {
            addCriterion("transportationplan is null");
            return (Criteria) this;
        }

        public Criteria andTransportationplanIsNotNull() {
            addCriterion("transportationplan is not null");
            return (Criteria) this;
        }

        public Criteria andTransportationplanEqualTo(Integer value) {
            addCriterion("transportationplan =", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanNotEqualTo(Integer value) {
            addCriterion("transportationplan <>", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanGreaterThan(Integer value) {
            addCriterion("transportationplan >", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanGreaterThanOrEqualTo(Integer value) {
            addCriterion("transportationplan >=", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanLessThan(Integer value) {
            addCriterion("transportationplan <", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanLessThanOrEqualTo(Integer value) {
            addCriterion("transportationplan <=", value, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanIn(List<Integer> values) {
            addCriterion("transportationplan in", values, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanNotIn(List<Integer> values) {
            addCriterion("transportationplan not in", values, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanBetween(Integer value1, Integer value2) {
            addCriterion("transportationplan between", value1, value2, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andTransportationplanNotBetween(Integer value1, Integer value2) {
            addCriterion("transportationplan not between", value1, value2, "transportationplan");
            return (Criteria) this;
        }

        public Criteria andSecurityletterIsNull() {
            addCriterion("securityletter is null");
            return (Criteria) this;
        }

        public Criteria andSecurityletterIsNotNull() {
            addCriterion("securityletter is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityletterEqualTo(Integer value) {
            addCriterion("securityletter =", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterNotEqualTo(Integer value) {
            addCriterion("securityletter <>", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterGreaterThan(Integer value) {
            addCriterion("securityletter >", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterGreaterThanOrEqualTo(Integer value) {
            addCriterion("securityletter >=", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterLessThan(Integer value) {
            addCriterion("securityletter <", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterLessThanOrEqualTo(Integer value) {
            addCriterion("securityletter <=", value, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterIn(List<Integer> values) {
            addCriterion("securityletter in", values, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterNotIn(List<Integer> values) {
            addCriterion("securityletter not in", values, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterBetween(Integer value1, Integer value2) {
            addCriterion("securityletter between", value1, value2, "securityletter");
            return (Criteria) this;
        }

        public Criteria andSecurityletterNotBetween(Integer value1, Integer value2) {
            addCriterion("securityletter not between", value1, value2, "securityletter");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andExportIsNull() {
            addCriterion("export is null");
            return (Criteria) this;
        }

        public Criteria andExportIsNotNull() {
            addCriterion("export is not null");
            return (Criteria) this;
        }

        public Criteria andExportEqualTo(Integer value) {
            addCriterion("export =", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportNotEqualTo(Integer value) {
            addCriterion("export <>", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportGreaterThan(Integer value) {
            addCriterion("export >", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportGreaterThanOrEqualTo(Integer value) {
            addCriterion("export >=", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportLessThan(Integer value) {
            addCriterion("export <", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportLessThanOrEqualTo(Integer value) {
            addCriterion("export <=", value, "export");
            return (Criteria) this;
        }

        public Criteria andExportIn(List<Integer> values) {
            addCriterion("export in", values, "export");
            return (Criteria) this;
        }

        public Criteria andExportNotIn(List<Integer> values) {
            addCriterion("export not in", values, "export");
            return (Criteria) this;
        }

        public Criteria andExportBetween(Integer value1, Integer value2) {
            addCriterion("export between", value1, value2, "export");
            return (Criteria) this;
        }

        public Criteria andExportNotBetween(Integer value1, Integer value2) {
            addCriterion("export not between", value1, value2, "export");
            return (Criteria) this;
        }

        public Criteria andStaircaseIsNull() {
            addCriterion("staircase is null");
            return (Criteria) this;
        }

        public Criteria andStaircaseIsNotNull() {
            addCriterion("staircase is not null");
            return (Criteria) this;
        }

        public Criteria andStaircaseEqualTo(String value) {
            addCriterion("staircase =", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseNotEqualTo(String value) {
            addCriterion("staircase <>", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseGreaterThan(String value) {
            addCriterion("staircase >", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseGreaterThanOrEqualTo(String value) {
            addCriterion("staircase >=", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseLessThan(String value) {
            addCriterion("staircase <", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseLessThanOrEqualTo(String value) {
            addCriterion("staircase <=", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseLike(String value) {
            addCriterion("staircase like", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseNotLike(String value) {
            addCriterion("staircase not like", value, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseIn(List<String> values) {
            addCriterion("staircase in", values, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseNotIn(List<String> values) {
            addCriterion("staircase not in", values, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseBetween(String value1, String value2) {
            addCriterion("staircase between", value1, value2, "staircase");
            return (Criteria) this;
        }

        public Criteria andStaircaseNotBetween(String value1, String value2) {
            addCriterion("staircase not between", value1, value2, "staircase");
            return (Criteria) this;
        }

        public Criteria andEgreedoorIsNull() {
            addCriterion("egreedoor is null");
            return (Criteria) this;
        }

        public Criteria andEgreedoorIsNotNull() {
            addCriterion("egreedoor is not null");
            return (Criteria) this;
        }

        public Criteria andEgreedoorEqualTo(Integer value) {
            addCriterion("egreedoor =", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorNotEqualTo(Integer value) {
            addCriterion("egreedoor <>", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorGreaterThan(Integer value) {
            addCriterion("egreedoor >", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorGreaterThanOrEqualTo(Integer value) {
            addCriterion("egreedoor >=", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorLessThan(Integer value) {
            addCriterion("egreedoor <", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorLessThanOrEqualTo(Integer value) {
            addCriterion("egreedoor <=", value, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorIn(List<Integer> values) {
            addCriterion("egreedoor in", values, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorNotIn(List<Integer> values) {
            addCriterion("egreedoor not in", values, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorBetween(Integer value1, Integer value2) {
            addCriterion("egreedoor between", value1, value2, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andEgreedoorNotBetween(Integer value1, Integer value2) {
            addCriterion("egreedoor not between", value1, value2, "egreedoor");
            return (Criteria) this;
        }

        public Criteria andFenceIsNull() {
            addCriterion("fence is null");
            return (Criteria) this;
        }

        public Criteria andFenceIsNotNull() {
            addCriterion("fence is not null");
            return (Criteria) this;
        }

        public Criteria andFenceEqualTo(Integer value) {
            addCriterion("fence =", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotEqualTo(Integer value) {
            addCriterion("fence <>", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceGreaterThan(Integer value) {
            addCriterion("fence >", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("fence >=", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceLessThan(Integer value) {
            addCriterion("fence <", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceLessThanOrEqualTo(Integer value) {
            addCriterion("fence <=", value, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceIn(List<Integer> values) {
            addCriterion("fence in", values, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotIn(List<Integer> values) {
            addCriterion("fence not in", values, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceBetween(Integer value1, Integer value2) {
            addCriterion("fence between", value1, value2, "fence");
            return (Criteria) this;
        }

        public Criteria andFenceNotBetween(Integer value1, Integer value2) {
            addCriterion("fence not between", value1, value2, "fence");
            return (Criteria) this;
        }

        public Criteria andEmergencylightIsNull() {
            addCriterion("emergencylight is null");
            return (Criteria) this;
        }

        public Criteria andEmergencylightIsNotNull() {
            addCriterion("emergencylight is not null");
            return (Criteria) this;
        }

        public Criteria andEmergencylightEqualTo(Integer value) {
            addCriterion("emergencylight =", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightNotEqualTo(Integer value) {
            addCriterion("emergencylight <>", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightGreaterThan(Integer value) {
            addCriterion("emergencylight >", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightGreaterThanOrEqualTo(Integer value) {
            addCriterion("emergencylight >=", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightLessThan(Integer value) {
            addCriterion("emergencylight <", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightLessThanOrEqualTo(Integer value) {
            addCriterion("emergencylight <=", value, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightIn(List<Integer> values) {
            addCriterion("emergencylight in", values, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightNotIn(List<Integer> values) {
            addCriterion("emergencylight not in", values, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightBetween(Integer value1, Integer value2) {
            addCriterion("emergencylight between", value1, value2, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andEmergencylightNotBetween(Integer value1, Integer value2) {
            addCriterion("emergencylight not between", value1, value2, "emergencylight");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(Integer value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(Integer value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(Integer value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(Integer value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(Integer value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<Integer> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<Integer> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(Integer value1, Integer value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(Integer value1, Integer value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andExtinguisherIsNull() {
            addCriterion("extinguisher is null");
            return (Criteria) this;
        }

        public Criteria andExtinguisherIsNotNull() {
            addCriterion("extinguisher is not null");
            return (Criteria) this;
        }

        public Criteria andExtinguisherEqualTo(Integer value) {
            addCriterion("extinguisher =", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherNotEqualTo(Integer value) {
            addCriterion("extinguisher <>", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherGreaterThan(Integer value) {
            addCriterion("extinguisher >", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherGreaterThanOrEqualTo(Integer value) {
            addCriterion("extinguisher >=", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherLessThan(Integer value) {
            addCriterion("extinguisher <", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherLessThanOrEqualTo(Integer value) {
            addCriterion("extinguisher <=", value, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherIn(List<Integer> values) {
            addCriterion("extinguisher in", values, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherNotIn(List<Integer> values) {
            addCriterion("extinguisher not in", values, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherBetween(Integer value1, Integer value2) {
            addCriterion("extinguisher between", value1, value2, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andExtinguisherNotBetween(Integer value1, Integer value2) {
            addCriterion("extinguisher not between", value1, value2, "extinguisher");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialIsNull() {
            addCriterion("decorativematerial is null");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialIsNotNull() {
            addCriterion("decorativematerial is not null");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialEqualTo(String value) {
            addCriterion("decorativematerial =", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialNotEqualTo(String value) {
            addCriterion("decorativematerial <>", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialGreaterThan(String value) {
            addCriterion("decorativematerial >", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialGreaterThanOrEqualTo(String value) {
            addCriterion("decorativematerial >=", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialLessThan(String value) {
            addCriterion("decorativematerial <", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialLessThanOrEqualTo(String value) {
            addCriterion("decorativematerial <=", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialLike(String value) {
            addCriterion("decorativematerial like", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialNotLike(String value) {
            addCriterion("decorativematerial not like", value, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialIn(List<String> values) {
            addCriterion("decorativematerial in", values, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialNotIn(List<String> values) {
            addCriterion("decorativematerial not in", values, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialBetween(String value1, String value2) {
            addCriterion("decorativematerial between", value1, value2, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andDecorativematerialNotBetween(String value1, String value2) {
            addCriterion("decorativematerial not between", value1, value2, "decorativematerial");
            return (Criteria) this;
        }

        public Criteria andLineIsNull() {
            addCriterion("line is null");
            return (Criteria) this;
        }

        public Criteria andLineIsNotNull() {
            addCriterion("line is not null");
            return (Criteria) this;
        }

        public Criteria andLineEqualTo(String value) {
            addCriterion("line =", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotEqualTo(String value) {
            addCriterion("line <>", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineGreaterThan(String value) {
            addCriterion("line >", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineGreaterThanOrEqualTo(String value) {
            addCriterion("line >=", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLessThan(String value) {
            addCriterion("line <", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLessThanOrEqualTo(String value) {
            addCriterion("line <=", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineLike(String value) {
            addCriterion("line like", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotLike(String value) {
            addCriterion("line not like", value, "line");
            return (Criteria) this;
        }

        public Criteria andLineIn(List<String> values) {
            addCriterion("line in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotIn(List<String> values) {
            addCriterion("line not in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineBetween(String value1, String value2) {
            addCriterion("line between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotBetween(String value1, String value2) {
            addCriterion("line not between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return (Criteria) this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("other =", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("other <>", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("other >", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("other >=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("other <", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("other <=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("other like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("other not like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherIn(List<String> values) {
            addCriterion("other in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotIn(List<String> values) {
            addCriterion("other not in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("other between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("other not between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andPolicemansignIsNull() {
            addCriterion("policemansign is null");
            return (Criteria) this;
        }

        public Criteria andPolicemansignIsNotNull() {
            addCriterion("policemansign is not null");
            return (Criteria) this;
        }

        public Criteria andPolicemansignEqualTo(String value) {
            addCriterion("policemansign =", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignNotEqualTo(String value) {
            addCriterion("policemansign <>", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignGreaterThan(String value) {
            addCriterion("policemansign >", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignGreaterThanOrEqualTo(String value) {
            addCriterion("policemansign >=", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignLessThan(String value) {
            addCriterion("policemansign <", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignLessThanOrEqualTo(String value) {
            addCriterion("policemansign <=", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignLike(String value) {
            addCriterion("policemansign like", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignNotLike(String value) {
            addCriterion("policemansign not like", value, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignIn(List<String> values) {
            addCriterion("policemansign in", values, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignNotIn(List<String> values) {
            addCriterion("policemansign not in", values, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignBetween(String value1, String value2) {
            addCriterion("policemansign between", value1, value2, "policemansign");
            return (Criteria) this;
        }

        public Criteria andPolicemansignNotBetween(String value1, String value2) {
            addCriterion("policemansign not between", value1, value2, "policemansign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignIsNull() {
            addCriterion("inspectorsign is null");
            return (Criteria) this;
        }

        public Criteria andInspectorsignIsNotNull() {
            addCriterion("inspectorsign is not null");
            return (Criteria) this;
        }

        public Criteria andInspectorsignEqualTo(String value) {
            addCriterion("inspectorsign =", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignNotEqualTo(String value) {
            addCriterion("inspectorsign <>", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignGreaterThan(String value) {
            addCriterion("inspectorsign >", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignGreaterThanOrEqualTo(String value) {
            addCriterion("inspectorsign >=", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignLessThan(String value) {
            addCriterion("inspectorsign <", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignLessThanOrEqualTo(String value) {
            addCriterion("inspectorsign <=", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignLike(String value) {
            addCriterion("inspectorsign like", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignNotLike(String value) {
            addCriterion("inspectorsign not like", value, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignIn(List<String> values) {
            addCriterion("inspectorsign in", values, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignNotIn(List<String> values) {
            addCriterion("inspectorsign not in", values, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignBetween(String value1, String value2) {
            addCriterion("inspectorsign between", value1, value2, "inspectorsign");
            return (Criteria) this;
        }

        public Criteria andInspectorsignNotBetween(String value1, String value2) {
            addCriterion("inspectorsign not between", value1, value2, "inspectorsign");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkrecord
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 31 11:55:13 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkrecord
     *
     * @mbggenerated Mon Oct 31 11:55:13 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}