package com.fire.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InspectionrecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public InspectionrecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNstitutionIsNull() {
            addCriterion("\" nstitution\" is null");
            return (Criteria) this;
        }

        public Criteria andNstitutionIsNotNull() {
            addCriterion("\" nstitution\" is not null");
            return (Criteria) this;
        }

        public Criteria andNstitutionEqualTo(String value) {
            addCriterion("\" nstitution\" =", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionNotEqualTo(String value) {
            addCriterion("\" nstitution\" <>", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionGreaterThan(String value) {
            addCriterion("\" nstitution\" >", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionGreaterThanOrEqualTo(String value) {
            addCriterion("\" nstitution\" >=", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionLessThan(String value) {
            addCriterion("\" nstitution\" <", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionLessThanOrEqualTo(String value) {
            addCriterion("\" nstitution\" <=", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionLike(String value) {
            addCriterion("\" nstitution\" like", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionNotLike(String value) {
            addCriterion("\" nstitution\" not like", value, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionIn(List<String> values) {
            addCriterion("\" nstitution\" in", values, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionNotIn(List<String> values) {
            addCriterion("\" nstitution\" not in", values, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionBetween(String value1, String value2) {
            addCriterion("\" nstitution\" between", value1, value2, "nstitution");
            return (Criteria) this;
        }

        public Criteria andNstitutionNotBetween(String value1, String value2) {
            addCriterion("\" nstitution\" not between", value1, value2, "nstitution");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeIsNull() {
            addCriterion("Personincharge is null");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeIsNotNull() {
            addCriterion("Personincharge is not null");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeEqualTo(String value) {
            addCriterion("Personincharge =", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeNotEqualTo(String value) {
            addCriterion("Personincharge <>", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeGreaterThan(String value) {
            addCriterion("Personincharge >", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeGreaterThanOrEqualTo(String value) {
            addCriterion("Personincharge >=", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeLessThan(String value) {
            addCriterion("Personincharge <", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeLessThanOrEqualTo(String value) {
            addCriterion("Personincharge <=", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeLike(String value) {
            addCriterion("Personincharge like", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeNotLike(String value) {
            addCriterion("Personincharge not like", value, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeIn(List<String> values) {
            addCriterion("Personincharge in", values, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeNotIn(List<String> values) {
            addCriterion("Personincharge not in", values, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeBetween(String value1, String value2) {
            addCriterion("Personincharge between", value1, value2, "personincharge");
            return (Criteria) this;
        }

        public Criteria andPersoninchargeNotBetween(String value1, String value2) {
            addCriterion("Personincharge not between", value1, value2, "personincharge");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("Category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("Category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("Category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("Category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("Category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("Category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("Category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("Category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("Category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("Category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("Category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("Category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("Category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("Category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("Area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("Area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Double value) {
            addCriterion("Area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Double value) {
            addCriterion("Area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Double value) {
            addCriterion("Area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Double value) {
            addCriterion("Area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Double value) {
            addCriterion("Area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Double value) {
            addCriterion("Area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Double> values) {
            addCriterion("Area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Double> values) {
            addCriterion("Area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Double value1, Double value2) {
            addCriterion("Area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Double value1, Double value2) {
            addCriterion("Area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNull() {
            addCriterion("Floors is null");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNotNull() {
            addCriterion("Floors is not null");
            return (Criteria) this;
        }

        public Criteria andFloorsEqualTo(Integer value) {
            addCriterion("Floors =", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotEqualTo(Integer value) {
            addCriterion("Floors <>", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThan(Integer value) {
            addCriterion("Floors >", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Floors >=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThan(Integer value) {
            addCriterion("Floors <", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThanOrEqualTo(Integer value) {
            addCriterion("Floors <=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsIn(List<Integer> values) {
            addCriterion("Floors in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotIn(List<Integer> values) {
            addCriterion("Floors not in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsBetween(Integer value1, Integer value2) {
            addCriterion("Floors between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotBetween(Integer value1, Integer value2) {
            addCriterion("Floors not between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("Height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("Height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("Height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("Height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("Height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("Height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("Height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("Height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("Height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("Height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("Height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("Height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andInspectorIsNull() {
            addCriterion("Inspector is null");
            return (Criteria) this;
        }

        public Criteria andInspectorIsNotNull() {
            addCriterion("Inspector is not null");
            return (Criteria) this;
        }

        public Criteria andInspectorEqualTo(String value) {
            addCriterion("Inspector =", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorNotEqualTo(String value) {
            addCriterion("Inspector <>", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorGreaterThan(String value) {
            addCriterion("Inspector >", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorGreaterThanOrEqualTo(String value) {
            addCriterion("Inspector >=", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorLessThan(String value) {
            addCriterion("Inspector <", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorLessThanOrEqualTo(String value) {
            addCriterion("Inspector <=", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorLike(String value) {
            addCriterion("Inspector like", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorNotLike(String value) {
            addCriterion("Inspector not like", value, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorIn(List<String> values) {
            addCriterion("Inspector in", values, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorNotIn(List<String> values) {
            addCriterion("Inspector not in", values, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorBetween(String value1, String value2) {
            addCriterion("Inspector between", value1, value2, "inspector");
            return (Criteria) this;
        }

        public Criteria andInspectorNotBetween(String value1, String value2) {
            addCriterion("Inspector not between", value1, value2, "inspector");
            return (Criteria) this;
        }

        public Criteria andEntourageIsNull() {
            addCriterion("Entourage is null");
            return (Criteria) this;
        }

        public Criteria andEntourageIsNotNull() {
            addCriterion("Entourage is not null");
            return (Criteria) this;
        }

        public Criteria andEntourageEqualTo(String value) {
            addCriterion("Entourage =", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageNotEqualTo(String value) {
            addCriterion("Entourage <>", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageGreaterThan(String value) {
            addCriterion("Entourage >", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageGreaterThanOrEqualTo(String value) {
            addCriterion("Entourage >=", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageLessThan(String value) {
            addCriterion("Entourage <", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageLessThanOrEqualTo(String value) {
            addCriterion("Entourage <=", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageLike(String value) {
            addCriterion("Entourage like", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageNotLike(String value) {
            addCriterion("Entourage not like", value, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageIn(List<String> values) {
            addCriterion("Entourage in", values, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageNotIn(List<String> values) {
            addCriterion("Entourage not in", values, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageBetween(String value1, String value2) {
            addCriterion("Entourage between", value1, value2, "entourage");
            return (Criteria) this;
        }

        public Criteria andEntourageNotBetween(String value1, String value2) {
            addCriterion("Entourage not between", value1, value2, "entourage");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNull() {
            addCriterion("Checkdate is null");
            return (Criteria) this;
        }

        public Criteria andCheckdateIsNotNull() {
            addCriterion("Checkdate is not null");
            return (Criteria) this;
        }

        public Criteria andCheckdateEqualTo(Date value) {
            addCriterion("Checkdate =", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotEqualTo(Date value) {
            addCriterion("Checkdate <>", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThan(Date value) {
            addCriterion("Checkdate >", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateGreaterThanOrEqualTo(Date value) {
            addCriterion("Checkdate >=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThan(Date value) {
            addCriterion("Checkdate <", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateLessThanOrEqualTo(Date value) {
            addCriterion("Checkdate <=", value, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateIn(List<Date> values) {
            addCriterion("Checkdate in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotIn(List<Date> values) {
            addCriterion("Checkdate not in", values, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateBetween(Date value1, Date value2) {
            addCriterion("Checkdate between", value1, value2, "checkdate");
            return (Criteria) this;
        }

        public Criteria andCheckdateNotBetween(Date value1, Date value2) {
            addCriterion("Checkdate not between", value1, value2, "checkdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspectionrecord
     *
     * @mbggenerated do_not_delete_during_merge Wed May 04 12:49:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inspectionrecord
     *
     * @mbggenerated Wed May 04 12:49:58 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}