package com.fire.po;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pictureid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    private Integer pictureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.firetableid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    private String firetableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.PicType
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    private String PicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pictureurl
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    private String pictureurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.uploadDate
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    private String uploaddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pictureid
     *
     * @return the value of picture.pictureid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public Integer getPictureid() {
        return pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pictureid
     *
     * @param pictureid the value for picture.pictureid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public void setPictureid(Integer pictureid) {
        this.pictureid = pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.firetableid
     *
     * @return the value of picture.firetableid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public String getFiretableid() {
        return firetableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.firetableid
     *
     * @param firetableid the value for picture.firetableid
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public void setFiretableid(String firetableid) {
        this.firetableid = firetableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.PicType
     *
     * @return the value of picture.PicType
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pictureurl
     *
     * @return the value of picture.pictureurl
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public String getPictureurl() {
        return pictureurl;
    }

    public String getPicType() {
		return PicType;
	}

	public void setPicType(String picType) {
		PicType = picType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pictureurl
     *
     * @param pictureurl the value for picture.pictureurl
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.uploadDate
     *
     * @return the value of picture.uploadDate
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public String getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.uploadDate
     *
     * @param uploaddate the value for picture.uploadDate
     *
     * @mbggenerated Thu Nov 24 21:35:51 CST 2016
     */
    public void setUploaddate(String uploaddate) {
        this.uploaddate = uploaddate;
    }

    @Override
    public String toString() {
        return "Picture{" +
                "pictureid=" + pictureid +
                ", firetableid='" + firetableid + '\'' +
                ", PicType='" + PicType + '\'' +
                ", pictureurl='" + pictureurl + '\'' +
                ", uploaddate='" + uploaddate + '\'' +
                '}';
    }
}