package com.fire.po;

import java.util.ArrayList;
import java.util.List;

public class PoliceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public PoliceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("Username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("Username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("Username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("Username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("Username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("Username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("Username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("Username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("Username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("Username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("Username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("Username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("Username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("Username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPozitionIsNull() {
            addCriterion("Pozition is null");
            return (Criteria) this;
        }

        public Criteria andPozitionIsNotNull() {
            addCriterion("Pozition is not null");
            return (Criteria) this;
        }

        public Criteria andPozitionEqualTo(String value) {
            addCriterion("Pozition =", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionNotEqualTo(String value) {
            addCriterion("Pozition <>", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionGreaterThan(String value) {
            addCriterion("Pozition >", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionGreaterThanOrEqualTo(String value) {
            addCriterion("Pozition >=", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionLessThan(String value) {
            addCriterion("Pozition <", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionLessThanOrEqualTo(String value) {
            addCriterion("Pozition <=", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionLike(String value) {
            addCriterion("Pozition like", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionNotLike(String value) {
            addCriterion("Pozition not like", value, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionIn(List<String> values) {
            addCriterion("Pozition in", values, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionNotIn(List<String> values) {
            addCriterion("Pozition not in", values, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionBetween(String value1, String value2) {
            addCriterion("Pozition between", value1, value2, "pozition");
            return (Criteria) this;
        }

        public Criteria andPozitionNotBetween(String value1, String value2) {
            addCriterion("Pozition not between", value1, value2, "pozition");
            return (Criteria) this;
        }

        public Criteria andUsercountIsNull() {
            addCriterion("Usercount is null");
            return (Criteria) this;
        }

        public Criteria andUsercountIsNotNull() {
            addCriterion("Usercount is not null");
            return (Criteria) this;
        }

        public Criteria andUsercountEqualTo(String value) {
            addCriterion("Usercount =", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountNotEqualTo(String value) {
            addCriterion("Usercount <>", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountGreaterThan(String value) {
            addCriterion("Usercount >", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountGreaterThanOrEqualTo(String value) {
            addCriterion("Usercount >=", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountLessThan(String value) {
            addCriterion("Usercount <", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountLessThanOrEqualTo(String value) {
            addCriterion("Usercount <=", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountLike(String value) {
            addCriterion("Usercount like", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountNotLike(String value) {
            addCriterion("Usercount not like", value, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountIn(List<String> values) {
            addCriterion("Usercount in", values, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountNotIn(List<String> values) {
            addCriterion("Usercount not in", values, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountBetween(String value1, String value2) {
            addCriterion("Usercount between", value1, value2, "usercount");
            return (Criteria) this;
        }

        public Criteria andUsercountNotBetween(String value1, String value2) {
            addCriterion("Usercount not between", value1, value2, "usercount");
            return (Criteria) this;
        }

        public Criteria andPcnumIsNull() {
            addCriterion("Pcnum is null");
            return (Criteria) this;
        }

        public Criteria andPcnumIsNotNull() {
            addCriterion("Pcnum is not null");
            return (Criteria) this;
        }

        public Criteria andPcnumEqualTo(String value) {
            addCriterion("Pcnum =", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumNotEqualTo(String value) {
            addCriterion("Pcnum <>", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumGreaterThan(String value) {
            addCriterion("Pcnum >", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumGreaterThanOrEqualTo(String value) {
            addCriterion("Pcnum >=", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumLessThan(String value) {
            addCriterion("Pcnum <", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumLessThanOrEqualTo(String value) {
            addCriterion("Pcnum <=", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumLike(String value) {
            addCriterion("Pcnum like", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumNotLike(String value) {
            addCriterion("Pcnum not like", value, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumIn(List<String> values) {
            addCriterion("Pcnum in", values, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumNotIn(List<String> values) {
            addCriterion("Pcnum not in", values, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumBetween(String value1, String value2) {
            addCriterion("Pcnum between", value1, value2, "pcnum");
            return (Criteria) this;
        }

        public Criteria andPcnumNotBetween(String value1, String value2) {
            addCriterion("Pcnum not between", value1, value2, "pcnum");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("Sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("Sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andPicstrIsNull() {
            addCriterion("Picstr is null");
            return (Criteria) this;
        }

        public Criteria andPicstrIsNotNull() {
            addCriterion("Picstr is not null");
            return (Criteria) this;
        }

        public Criteria andPicstrEqualTo(String value) {
            addCriterion("Picstr =", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrNotEqualTo(String value) {
            addCriterion("Picstr <>", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrGreaterThan(String value) {
            addCriterion("Picstr >", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrGreaterThanOrEqualTo(String value) {
            addCriterion("Picstr >=", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrLessThan(String value) {
            addCriterion("Picstr <", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrLessThanOrEqualTo(String value) {
            addCriterion("Picstr <=", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrLike(String value) {
            addCriterion("Picstr like", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrNotLike(String value) {
            addCriterion("Picstr not like", value, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrIn(List<String> values) {
            addCriterion("Picstr in", values, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrNotIn(List<String> values) {
            addCriterion("Picstr not in", values, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrBetween(String value1, String value2) {
            addCriterion("Picstr between", value1, value2, "picstr");
            return (Criteria) this;
        }

        public Criteria andPicstrNotBetween(String value1, String value2) {
            addCriterion("Picstr not between", value1, value2, "picstr");
            return (Criteria) this;
        }

        public Criteria andUserlimitIsNull() {
            addCriterion("Userlimit is null");
            return (Criteria) this;
        }

        public Criteria andUserlimitIsNotNull() {
            addCriterion("Userlimit is not null");
            return (Criteria) this;
        }

        public Criteria andUserlimitEqualTo(Integer value) {
            addCriterion("Userlimit =", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitNotEqualTo(Integer value) {
            addCriterion("Userlimit <>", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitGreaterThan(Integer value) {
            addCriterion("Userlimit >", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("Userlimit >=", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitLessThan(Integer value) {
            addCriterion("Userlimit <", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitLessThanOrEqualTo(Integer value) {
            addCriterion("Userlimit <=", value, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitIn(List<Integer> values) {
            addCriterion("Userlimit in", values, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitNotIn(List<Integer> values) {
            addCriterion("Userlimit not in", values, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitBetween(Integer value1, Integer value2) {
            addCriterion("Userlimit between", value1, value2, "userlimit");
            return (Criteria) this;
        }

        public Criteria andUserlimitNotBetween(Integer value1, Integer value2) {
            addCriterion("Userlimit not between", value1, value2, "userlimit");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("Email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("Email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("Email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("Email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("Email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("Email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("Email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("Email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("Email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("Email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("Email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("Email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("Email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPoliceidIsNull() {
            addCriterion("Policeid is null");
            return (Criteria) this;
        }

        public Criteria andPoliceidIsNotNull() {
            addCriterion("Policeid is not null");
            return (Criteria) this;
        }

        public Criteria andPoliceidEqualTo(Integer value) {
            addCriterion("Policeid =", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidNotEqualTo(Integer value) {
            addCriterion("Policeid <>", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidGreaterThan(Integer value) {
            addCriterion("Policeid >", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Policeid >=", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidLessThan(Integer value) {
            addCriterion("Policeid <", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidLessThanOrEqualTo(Integer value) {
            addCriterion("Policeid <=", value, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidIn(List<Integer> values) {
            addCriterion("Policeid in", values, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidNotIn(List<Integer> values) {
            addCriterion("Policeid not in", values, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidBetween(Integer value1, Integer value2) {
            addCriterion("Policeid between", value1, value2, "policeid");
            return (Criteria) this;
        }

        public Criteria andPoliceidNotBetween(Integer value1, Integer value2) {
            addCriterion("Policeid not between", value1, value2, "policeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table police
     *
     * @mbggenerated do_not_delete_during_merge Wed May 04 13:11:26 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table police
     *
     * @mbggenerated Wed May 04 13:11:26 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}