package com.fire.po;

public class Role {
	
    private Integer roleid;
    
    private String usertype;

    private String userlimit;

    public Integer getRoleid() {
        return roleid;
    }

    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.usertype
     *
     * @return the value of role.usertype
     *
     * @mbggenerated Sun Jul 17 16:50:10 CST 2016
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.usertype
     *
     * @param usertype the value for role.usertype
     *
     * @mbggenerated Sun Jul 17 16:50:10 CST 2016
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.userlimit
     *
     * @return the value of role.userlimit
     *
     * @mbggenerated Sun Jul 17 16:50:10 CST 2016
     */
    public String getUserlimit() {
        return userlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.userlimit
     *
     * @param userlimit the value for role.userlimit
     *
     * @mbggenerated Sun Jul 17 16:50:10 CST 2016
     */
    public void setUserlimit(String userlimit) {
        this.userlimit = userlimit;
    }
}