package com.fire.po;

public class Transfertable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.transfertableid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String transfertableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.userid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.unitid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private Integer unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.unitname
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String unitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.address
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.area
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.floors
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String floors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.height
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.islevel
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String islevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.risk
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String risk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.firedapartment
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String firedapartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.masterials
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String masterials;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.transferdate
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String transferdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.branch
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfertable.policestation
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    private String policestation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.transfertableid
     *
     * @return the value of transfertable.transfertableid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getTransfertableid() {
        return transfertableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.transfertableid
     *
     * @param transfertableid the value for transfertable.transfertableid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setTransfertableid(String transfertableid) {
        this.transfertableid = transfertableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.userid
     *
     * @return the value of transfertable.userid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.userid
     *
     * @param userid the value for transfertable.userid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.unitid
     *
     * @return the value of transfertable.unitid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.unitid
     *
     * @param unitid the value for transfertable.unitid
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.unitname
     *
     * @return the value of transfertable.unitname
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.unitname
     *
     * @param unitname the value for transfertable.unitname
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.address
     *
     * @return the value of transfertable.address
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.address
     *
     * @param address the value for transfertable.address
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.area
     *
     * @return the value of transfertable.area
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.area
     *
     * @param area the value for transfertable.area
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.floors
     *
     * @return the value of transfertable.floors
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getFloors() {
        return floors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.floors
     *
     * @param floors the value for transfertable.floors
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setFloors(String floors) {
        this.floors = floors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.height
     *
     * @return the value of transfertable.height
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.height
     *
     * @param height the value for transfertable.height
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.islevel
     *
     * @return the value of transfertable.islevel
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getIslevel() {
        return islevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.islevel
     *
     * @param islevel the value for transfertable.islevel
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setIslevel(String islevel) {
        this.islevel = islevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.risk
     *
     * @return the value of transfertable.risk
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.risk
     *
     * @param risk the value for transfertable.risk
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setRisk(String risk) {
        this.risk = risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.firedapartment
     *
     * @return the value of transfertable.firedapartment
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getFiredapartment() {
        return firedapartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.firedapartment
     *
     * @param firedapartment the value for transfertable.firedapartment
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setFiredapartment(String firedapartment) {
        this.firedapartment = firedapartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.masterials
     *
     * @return the value of transfertable.masterials
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getMasterials() {
        return masterials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.masterials
     *
     * @param masterials the value for transfertable.masterials
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setMasterials(String masterials) {
        this.masterials = masterials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.transferdate
     *
     * @return the value of transfertable.transferdate
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getTransferdate() {
        return transferdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.transferdate
     *
     * @param transferdate the value for transfertable.transferdate
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setTransferdate(String transferdate) {
        this.transferdate = transferdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.branch
     *
     * @return the value of transfertable.branch
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.branch
     *
     * @param branch the value for transfertable.branch
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfertable.policestation
     *
     * @return the value of transfertable.policestation
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getPolicestation() {
        return policestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfertable.policestation
     *
     * @param policestation the value for transfertable.policestation
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setPolicestation(String policestation) {
        this.policestation = policestation;
    }

    @Override
    public String toString() {
        return "Transfertable{" +
                "transfertableid='" + transfertableid + '\'' +
                ", userid=" + userid +
                ", unitid=" + unitid +
                ", unitname='" + unitname + '\'' +
                ", address='" + address + '\'' +
                ", area='" + area + '\'' +
                ", floors='" + floors + '\'' +
                ", height=" + height +
                ", islevel='" + islevel + '\'' +
                ", risk='" + risk + '\'' +
                ", firedapartment='" + firedapartment + '\'' +
                ", masterials='" + masterials + '\'' +
                ", transferdate='" + transferdate + '\'' +
                ", branch='" + branch + '\'' +
                ", policestation='" + policestation + '\'' +
                '}';
    }
}