package com.fire.po;

import java.util.ArrayList;
import java.util.List;

public class TransfertableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public TransfertableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransfertableidIsNull() {
            addCriterion("transfertableid is null");
            return (Criteria) this;
        }

        public Criteria andTransfertableidIsNotNull() {
            addCriterion("transfertableid is not null");
            return (Criteria) this;
        }

        public Criteria andTransfertableidEqualTo(Integer value) {
            addCriterion("transfertableid =", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidNotEqualTo(Integer value) {
            addCriterion("transfertableid <>", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidGreaterThan(Integer value) {
            addCriterion("transfertableid >", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidGreaterThanOrEqualTo(Integer value) {
            addCriterion("transfertableid >=", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidLessThan(Integer value) {
            addCriterion("transfertableid <", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidLessThanOrEqualTo(Integer value) {
            addCriterion("transfertableid <=", value, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidIn(List<Integer> values) {
            addCriterion("transfertableid in", values, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidNotIn(List<Integer> values) {
            addCriterion("transfertableid not in", values, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidBetween(Integer value1, Integer value2) {
            addCriterion("transfertableid between", value1, value2, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andTransfertableidNotBetween(Integer value1, Integer value2) {
            addCriterion("transfertableid not between", value1, value2, "transfertableid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNull() {
            addCriterion("unitid is null");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNotNull() {
            addCriterion("unitid is not null");
            return (Criteria) this;
        }

        public Criteria andUnitidEqualTo(Integer value) {
            addCriterion("unitid =", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotEqualTo(Integer value) {
            addCriterion("unitid <>", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThan(Integer value) {
            addCriterion("unitid >", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unitid >=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThan(Integer value) {
            addCriterion("unitid <", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThanOrEqualTo(Integer value) {
            addCriterion("unitid <=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidIn(List<Integer> values) {
            addCriterion("unitid in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotIn(List<Integer> values) {
            addCriterion("unitid not in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidBetween(Integer value1, Integer value2) {
            addCriterion("unitid between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotBetween(Integer value1, Integer value2) {
            addCriterion("unitid not between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNull() {
            addCriterion("unitname is null");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNotNull() {
            addCriterion("unitname is not null");
            return (Criteria) this;
        }

        public Criteria andUnitnameEqualTo(String value) {
            addCriterion("unitname =", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotEqualTo(String value) {
            addCriterion("unitname <>", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThan(String value) {
            addCriterion("unitname >", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThanOrEqualTo(String value) {
            addCriterion("unitname >=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThan(String value) {
            addCriterion("unitname <", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThanOrEqualTo(String value) {
            addCriterion("unitname <=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLike(String value) {
            addCriterion("unitname like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotLike(String value) {
            addCriterion("unitname not like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameIn(List<String> values) {
            addCriterion("unitname in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotIn(List<String> values) {
            addCriterion("unitname not in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameBetween(String value1, String value2) {
            addCriterion("unitname between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotBetween(String value1, String value2) {
            addCriterion("unitname not between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNull() {
            addCriterion("floors is null");
            return (Criteria) this;
        }

        public Criteria andFloorsIsNotNull() {
            addCriterion("floors is not null");
            return (Criteria) this;
        }

        public Criteria andFloorsEqualTo(String value) {
            addCriterion("floors =", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotEqualTo(String value) {
            addCriterion("floors <>", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThan(String value) {
            addCriterion("floors >", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsGreaterThanOrEqualTo(String value) {
            addCriterion("floors >=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThan(String value) {
            addCriterion("floors <", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLessThanOrEqualTo(String value) {
            addCriterion("floors <=", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsLike(String value) {
            addCriterion("floors like", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotLike(String value) {
            addCriterion("floors not like", value, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsIn(List<String> values) {
            addCriterion("floors in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotIn(List<String> values) {
            addCriterion("floors not in", values, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsBetween(String value1, String value2) {
            addCriterion("floors between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andFloorsNotBetween(String value1, String value2) {
            addCriterion("floors not between", value1, value2, "floors");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andIslevelIsNull() {
            addCriterion("islevel is null");
            return (Criteria) this;
        }

        public Criteria andIslevelIsNotNull() {
            addCriterion("islevel is not null");
            return (Criteria) this;
        }

        public Criteria andIslevelEqualTo(String value) {
            addCriterion("islevel =", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelNotEqualTo(String value) {
            addCriterion("islevel <>", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelGreaterThan(String value) {
            addCriterion("islevel >", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelGreaterThanOrEqualTo(String value) {
            addCriterion("islevel >=", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelLessThan(String value) {
            addCriterion("islevel <", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelLessThanOrEqualTo(String value) {
            addCriterion("islevel <=", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelLike(String value) {
            addCriterion("islevel like", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelNotLike(String value) {
            addCriterion("islevel not like", value, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelIn(List<String> values) {
            addCriterion("islevel in", values, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelNotIn(List<String> values) {
            addCriterion("islevel not in", values, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelBetween(String value1, String value2) {
            addCriterion("islevel between", value1, value2, "islevel");
            return (Criteria) this;
        }

        public Criteria andIslevelNotBetween(String value1, String value2) {
            addCriterion("islevel not between", value1, value2, "islevel");
            return (Criteria) this;
        }

        public Criteria andRiskIsNull() {
            addCriterion("risk is null");
            return (Criteria) this;
        }

        public Criteria andRiskIsNotNull() {
            addCriterion("risk is not null");
            return (Criteria) this;
        }

        public Criteria andRiskEqualTo(String value) {
            addCriterion("risk =", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotEqualTo(String value) {
            addCriterion("risk <>", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskGreaterThan(String value) {
            addCriterion("risk >", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskGreaterThanOrEqualTo(String value) {
            addCriterion("risk >=", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskLessThan(String value) {
            addCriterion("risk <", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskLessThanOrEqualTo(String value) {
            addCriterion("risk <=", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskLike(String value) {
            addCriterion("risk like", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotLike(String value) {
            addCriterion("risk not like", value, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskIn(List<String> values) {
            addCriterion("risk in", values, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotIn(List<String> values) {
            addCriterion("risk not in", values, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskBetween(String value1, String value2) {
            addCriterion("risk between", value1, value2, "risk");
            return (Criteria) this;
        }

        public Criteria andRiskNotBetween(String value1, String value2) {
            addCriterion("risk not between", value1, value2, "risk");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentIsNull() {
            addCriterion("firedapartment is null");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentIsNotNull() {
            addCriterion("firedapartment is not null");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentEqualTo(String value) {
            addCriterion("firedapartment =", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentNotEqualTo(String value) {
            addCriterion("firedapartment <>", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentGreaterThan(String value) {
            addCriterion("firedapartment >", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentGreaterThanOrEqualTo(String value) {
            addCriterion("firedapartment >=", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentLessThan(String value) {
            addCriterion("firedapartment <", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentLessThanOrEqualTo(String value) {
            addCriterion("firedapartment <=", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentLike(String value) {
            addCriterion("firedapartment like", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentNotLike(String value) {
            addCriterion("firedapartment not like", value, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentIn(List<String> values) {
            addCriterion("firedapartment in", values, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentNotIn(List<String> values) {
            addCriterion("firedapartment not in", values, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentBetween(String value1, String value2) {
            addCriterion("firedapartment between", value1, value2, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andFiredapartmentNotBetween(String value1, String value2) {
            addCriterion("firedapartment not between", value1, value2, "firedapartment");
            return (Criteria) this;
        }

        public Criteria andMasterialsIsNull() {
            addCriterion("masterials is null");
            return (Criteria) this;
        }

        public Criteria andMasterialsIsNotNull() {
            addCriterion("masterials is not null");
            return (Criteria) this;
        }

        public Criteria andMasterialsEqualTo(String value) {
            addCriterion("masterials =", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsNotEqualTo(String value) {
            addCriterion("masterials <>", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsGreaterThan(String value) {
            addCriterion("masterials >", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsGreaterThanOrEqualTo(String value) {
            addCriterion("masterials >=", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsLessThan(String value) {
            addCriterion("masterials <", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsLessThanOrEqualTo(String value) {
            addCriterion("masterials <=", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsLike(String value) {
            addCriterion("masterials like", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsNotLike(String value) {
            addCriterion("masterials not like", value, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsIn(List<String> values) {
            addCriterion("masterials in", values, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsNotIn(List<String> values) {
            addCriterion("masterials not in", values, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsBetween(String value1, String value2) {
            addCriterion("masterials between", value1, value2, "masterials");
            return (Criteria) this;
        }

        public Criteria andMasterialsNotBetween(String value1, String value2) {
            addCriterion("masterials not between", value1, value2, "masterials");
            return (Criteria) this;
        }

        public Criteria andTransferdateIsNull() {
            addCriterion("transferdate is null");
            return (Criteria) this;
        }

        public Criteria andTransferdateIsNotNull() {
            addCriterion("transferdate is not null");
            return (Criteria) this;
        }

        public Criteria andTransferdateEqualTo(String value) {
            addCriterion("transferdate =", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateNotEqualTo(String value) {
            addCriterion("transferdate <>", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateGreaterThan(String value) {
            addCriterion("transferdate >", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateGreaterThanOrEqualTo(String value) {
            addCriterion("transferdate >=", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateLessThan(String value) {
            addCriterion("transferdate <", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateLessThanOrEqualTo(String value) {
            addCriterion("transferdate <=", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateLike(String value) {
            addCriterion("transferdate like", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateNotLike(String value) {
            addCriterion("transferdate not like", value, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateIn(List<String> values) {
            addCriterion("transferdate in", values, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateNotIn(List<String> values) {
            addCriterion("transferdate not in", values, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateBetween(String value1, String value2) {
            addCriterion("transferdate between", value1, value2, "transferdate");
            return (Criteria) this;
        }

        public Criteria andTransferdateNotBetween(String value1, String value2) {
            addCriterion("transferdate not between", value1, value2, "transferdate");
            return (Criteria) this;
        }

        public Criteria andBranchIsNull() {
            addCriterion("branch is null");
            return (Criteria) this;
        }

        public Criteria andBranchIsNotNull() {
            addCriterion("branch is not null");
            return (Criteria) this;
        }

        public Criteria andBranchEqualTo(String value) {
            addCriterion("branch =", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotEqualTo(String value) {
            addCriterion("branch <>", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThan(String value) {
            addCriterion("branch >", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThanOrEqualTo(String value) {
            addCriterion("branch >=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThan(String value) {
            addCriterion("branch <", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThanOrEqualTo(String value) {
            addCriterion("branch <=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLike(String value) {
            addCriterion("branch like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotLike(String value) {
            addCriterion("branch not like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchIn(List<String> values) {
            addCriterion("branch in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotIn(List<String> values) {
            addCriterion("branch not in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchBetween(String value1, String value2) {
            addCriterion("branch between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotBetween(String value1, String value2) {
            addCriterion("branch not between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andPolicestationIsNull() {
            addCriterion("policestation is null");
            return (Criteria) this;
        }

        public Criteria andPolicestationIsNotNull() {
            addCriterion("policestation is not null");
            return (Criteria) this;
        }

        public Criteria andPolicestationEqualTo(String value) {
            addCriterion("policestation =", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationNotEqualTo(String value) {
            addCriterion("policestation <>", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationGreaterThan(String value) {
            addCriterion("policestation >", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationGreaterThanOrEqualTo(String value) {
            addCriterion("policestation >=", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationLessThan(String value) {
            addCriterion("policestation <", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationLessThanOrEqualTo(String value) {
            addCriterion("policestation <=", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationLike(String value) {
            addCriterion("policestation like", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationNotLike(String value) {
            addCriterion("policestation not like", value, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationIn(List<String> values) {
            addCriterion("policestation in", values, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationNotIn(List<String> values) {
            addCriterion("policestation not in", values, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationBetween(String value1, String value2) {
            addCriterion("policestation between", value1, value2, "policestation");
            return (Criteria) this;
        }

        public Criteria andPolicestationNotBetween(String value1, String value2) {
            addCriterion("policestation not between", value1, value2, "policestation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfertable
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 09 18:00:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transfertable
     *
     * @mbggenerated Sun Oct 09 18:00:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}