package com.fire.po;

import java.util.ArrayList;
import java.util.List;

public class TroubletableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public TroubletableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTroubletableidIsNull() {
            addCriterion("troubletableid is null");
            return (Criteria) this;
        }

        public Criteria andTroubletableidIsNotNull() {
            addCriterion("troubletableid is not null");
            return (Criteria) this;
        }

        public Criteria andTroubletableidEqualTo(Integer value) {
            addCriterion("troubletableid =", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidNotEqualTo(Integer value) {
            addCriterion("troubletableid <>", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidGreaterThan(Integer value) {
            addCriterion("troubletableid >", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidGreaterThanOrEqualTo(Integer value) {
            addCriterion("troubletableid >=", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidLessThan(Integer value) {
            addCriterion("troubletableid <", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidLessThanOrEqualTo(Integer value) {
            addCriterion("troubletableid <=", value, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidIn(List<Integer> values) {
            addCriterion("troubletableid in", values, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidNotIn(List<Integer> values) {
            addCriterion("troubletableid not in", values, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidBetween(Integer value1, Integer value2) {
            addCriterion("troubletableid between", value1, value2, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andTroubletableidNotBetween(Integer value1, Integer value2) {
            addCriterion("troubletableid not between", value1, value2, "troubletableid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNull() {
            addCriterion("unitid is null");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNotNull() {
            addCriterion("unitid is not null");
            return (Criteria) this;
        }

        public Criteria andUnitidEqualTo(Integer value) {
            addCriterion("unitid =", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotEqualTo(Integer value) {
            addCriterion("unitid <>", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThan(Integer value) {
            addCriterion("unitid >", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unitid >=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThan(Integer value) {
            addCriterion("unitid <", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThanOrEqualTo(Integer value) {
            addCriterion("unitid <=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidIn(List<Integer> values) {
            addCriterion("unitid in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotIn(List<Integer> values) {
            addCriterion("unitid not in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidBetween(Integer value1, Integer value2) {
            addCriterion("unitid between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotBetween(Integer value1, Integer value2) {
            addCriterion("unitid not between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNull() {
            addCriterion("organization is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNotNull() {
            addCriterion("organization is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationEqualTo(String value) {
            addCriterion("organization =", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotEqualTo(String value) {
            addCriterion("organization <>", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThan(String value) {
            addCriterion("organization >", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThanOrEqualTo(String value) {
            addCriterion("organization >=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThan(String value) {
            addCriterion("organization <", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThanOrEqualTo(String value) {
            addCriterion("organization <=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLike(String value) {
            addCriterion("organization like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotLike(String value) {
            addCriterion("organization not like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationIn(List<String> values) {
            addCriterion("organization in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotIn(List<String> values) {
            addCriterion("organization not in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationBetween(String value1, String value2) {
            addCriterion("organization between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotBetween(String value1, String value2) {
            addCriterion("organization not between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("year like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("year not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("month like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("month not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(String value) {
            addCriterion("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(String value) {
            addCriterion("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(String value) {
            addCriterion("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(String value) {
            addCriterion("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(String value) {
            addCriterion("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(String value) {
            addCriterion("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLike(String value) {
            addCriterion("day like", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotLike(String value) {
            addCriterion("day not like", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<String> values) {
            addCriterion("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<String> values) {
            addCriterion("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(String value1, String value2) {
            addCriterion("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(String value1, String value2) {
            addCriterion("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNull() {
            addCriterion("unitname is null");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNotNull() {
            addCriterion("unitname is not null");
            return (Criteria) this;
        }

        public Criteria andUnitnameEqualTo(String value) {
            addCriterion("unitname =", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotEqualTo(String value) {
            addCriterion("unitname <>", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThan(String value) {
            addCriterion("unitname >", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThanOrEqualTo(String value) {
            addCriterion("unitname >=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThan(String value) {
            addCriterion("unitname <", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThanOrEqualTo(String value) {
            addCriterion("unitname <=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLike(String value) {
            addCriterion("unitname like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotLike(String value) {
            addCriterion("unitname not like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameIn(List<String> values) {
            addCriterion("unitname in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotIn(List<String> values) {
            addCriterion("unitname not in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameBetween(String value1, String value2) {
            addCriterion("unitname between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotBetween(String value1, String value2) {
            addCriterion("unitname not between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andRisk1IsNull() {
            addCriterion("risk1 is null");
            return (Criteria) this;
        }

        public Criteria andRisk1IsNotNull() {
            addCriterion("risk1 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk1EqualTo(Integer value) {
            addCriterion("risk1 =", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1NotEqualTo(Integer value) {
            addCriterion("risk1 <>", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1GreaterThan(Integer value) {
            addCriterion("risk1 >", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk1 >=", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1LessThan(Integer value) {
            addCriterion("risk1 <", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1LessThanOrEqualTo(Integer value) {
            addCriterion("risk1 <=", value, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1In(List<Integer> values) {
            addCriterion("risk1 in", values, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1NotIn(List<Integer> values) {
            addCriterion("risk1 not in", values, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1Between(Integer value1, Integer value2) {
            addCriterion("risk1 between", value1, value2, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk1NotBetween(Integer value1, Integer value2) {
            addCriterion("risk1 not between", value1, value2, "risk1");
            return (Criteria) this;
        }

        public Criteria andRisk2IsNull() {
            addCriterion("risk2 is null");
            return (Criteria) this;
        }

        public Criteria andRisk2IsNotNull() {
            addCriterion("risk2 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk2EqualTo(Integer value) {
            addCriterion("risk2 =", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2NotEqualTo(Integer value) {
            addCriterion("risk2 <>", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2GreaterThan(Integer value) {
            addCriterion("risk2 >", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk2 >=", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2LessThan(Integer value) {
            addCriterion("risk2 <", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2LessThanOrEqualTo(Integer value) {
            addCriterion("risk2 <=", value, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2In(List<Integer> values) {
            addCriterion("risk2 in", values, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2NotIn(List<Integer> values) {
            addCriterion("risk2 not in", values, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2Between(Integer value1, Integer value2) {
            addCriterion("risk2 between", value1, value2, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk2NotBetween(Integer value1, Integer value2) {
            addCriterion("risk2 not between", value1, value2, "risk2");
            return (Criteria) this;
        }

        public Criteria andRisk3IsNull() {
            addCriterion("risk3 is null");
            return (Criteria) this;
        }

        public Criteria andRisk3IsNotNull() {
            addCriterion("risk3 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk3EqualTo(Integer value) {
            addCriterion("risk3 =", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3NotEqualTo(Integer value) {
            addCriterion("risk3 <>", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3GreaterThan(Integer value) {
            addCriterion("risk3 >", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk3 >=", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3LessThan(Integer value) {
            addCriterion("risk3 <", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3LessThanOrEqualTo(Integer value) {
            addCriterion("risk3 <=", value, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3In(List<Integer> values) {
            addCriterion("risk3 in", values, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3NotIn(List<Integer> values) {
            addCriterion("risk3 not in", values, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3Between(Integer value1, Integer value2) {
            addCriterion("risk3 between", value1, value2, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk3NotBetween(Integer value1, Integer value2) {
            addCriterion("risk3 not between", value1, value2, "risk3");
            return (Criteria) this;
        }

        public Criteria andRisk4IsNull() {
            addCriterion("risk4 is null");
            return (Criteria) this;
        }

        public Criteria andRisk4IsNotNull() {
            addCriterion("risk4 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk4EqualTo(Integer value) {
            addCriterion("risk4 =", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4NotEqualTo(Integer value) {
            addCriterion("risk4 <>", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4GreaterThan(Integer value) {
            addCriterion("risk4 >", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk4 >=", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4LessThan(Integer value) {
            addCriterion("risk4 <", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4LessThanOrEqualTo(Integer value) {
            addCriterion("risk4 <=", value, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4In(List<Integer> values) {
            addCriterion("risk4 in", values, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4NotIn(List<Integer> values) {
            addCriterion("risk4 not in", values, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4Between(Integer value1, Integer value2) {
            addCriterion("risk4 between", value1, value2, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk4NotBetween(Integer value1, Integer value2) {
            addCriterion("risk4 not between", value1, value2, "risk4");
            return (Criteria) this;
        }

        public Criteria andRisk5IsNull() {
            addCriterion("risk5 is null");
            return (Criteria) this;
        }

        public Criteria andRisk5IsNotNull() {
            addCriterion("risk5 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk5EqualTo(Integer value) {
            addCriterion("risk5 =", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5NotEqualTo(Integer value) {
            addCriterion("risk5 <>", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5GreaterThan(Integer value) {
            addCriterion("risk5 >", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk5 >=", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5LessThan(Integer value) {
            addCriterion("risk5 <", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5LessThanOrEqualTo(Integer value) {
            addCriterion("risk5 <=", value, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5In(List<Integer> values) {
            addCriterion("risk5 in", values, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5NotIn(List<Integer> values) {
            addCriterion("risk5 not in", values, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5Between(Integer value1, Integer value2) {
            addCriterion("risk5 between", value1, value2, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk5NotBetween(Integer value1, Integer value2) {
            addCriterion("risk5 not between", value1, value2, "risk5");
            return (Criteria) this;
        }

        public Criteria andRisk6IsNull() {
            addCriterion("risk6 is null");
            return (Criteria) this;
        }

        public Criteria andRisk6IsNotNull() {
            addCriterion("risk6 is not null");
            return (Criteria) this;
        }

        public Criteria andRisk6EqualTo(Integer value) {
            addCriterion("risk6 =", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6NotEqualTo(Integer value) {
            addCriterion("risk6 <>", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6GreaterThan(Integer value) {
            addCriterion("risk6 >", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6GreaterThanOrEqualTo(Integer value) {
            addCriterion("risk6 >=", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6LessThan(Integer value) {
            addCriterion("risk6 <", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6LessThanOrEqualTo(Integer value) {
            addCriterion("risk6 <=", value, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6In(List<Integer> values) {
            addCriterion("risk6 in", values, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6NotIn(List<Integer> values) {
            addCriterion("risk6 not in", values, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6Between(Integer value1, Integer value2) {
            addCriterion("risk6 between", value1, value2, "risk6");
            return (Criteria) this;
        }

        public Criteria andRisk6NotBetween(Integer value1, Integer value2) {
            addCriterion("risk6 not between", value1, value2, "risk6");
            return (Criteria) this;
        }

        public Criteria andOtherriskIsNull() {
            addCriterion("otherrisk is null");
            return (Criteria) this;
        }

        public Criteria andOtherriskIsNotNull() {
            addCriterion("otherrisk is not null");
            return (Criteria) this;
        }

        public Criteria andOtherriskEqualTo(Integer value) {
            addCriterion("otherrisk =", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskNotEqualTo(Integer value) {
            addCriterion("otherrisk <>", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskGreaterThan(Integer value) {
            addCriterion("otherrisk >", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskGreaterThanOrEqualTo(Integer value) {
            addCriterion("otherrisk >=", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskLessThan(Integer value) {
            addCriterion("otherrisk <", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskLessThanOrEqualTo(Integer value) {
            addCriterion("otherrisk <=", value, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskIn(List<Integer> values) {
            addCriterion("otherrisk in", values, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskNotIn(List<Integer> values) {
            addCriterion("otherrisk not in", values, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskBetween(Integer value1, Integer value2) {
            addCriterion("otherrisk between", value1, value2, "otherrisk");
            return (Criteria) this;
        }

        public Criteria andOtherriskNotBetween(Integer value1, Integer value2) {
            addCriterion("otherrisk not between", value1, value2, "otherrisk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table troubletable
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 08 15:37:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table troubletable
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}