package com.fire.po;

public class Troubletable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.troubletableid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String troubletableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.userid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.unitid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.organization
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.year
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.month
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.day
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.unitname
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private String unitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk1
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk2
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk3
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk4
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk5
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.risk6
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer risk6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troubletable.otherrisk
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    private Integer otherrisk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.troubletableid
     *
     * @return the value of troubletable.troubletableid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getTroubletableid() {
        return troubletableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.troubletableid
     *
     * @param troubletableid the value for troubletable.troubletableid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setTroubletableid(String troubletableid) {
        this.troubletableid = troubletableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.userid
     *
     * @return the value of troubletable.userid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.userid
     *
     * @param userid the value for troubletable.userid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.unitid
     *
     * @return the value of troubletable.unitid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.unitid
     *
     * @param unitid the value for troubletable.unitid
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.organization
     *
     * @return the value of troubletable.organization
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.organization
     *
     * @param organization the value for troubletable.organization
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.year
     *
     * @return the value of troubletable.year
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.year
     *
     * @param year the value for troubletable.year
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.month
     *
     * @return the value of troubletable.month
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.month
     *
     * @param month the value for troubletable.month
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.day
     *
     * @return the value of troubletable.day
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.day
     *
     * @param day the value for troubletable.day
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.unitname
     *
     * @return the value of troubletable.unitname
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.unitname
     *
     * @param unitname the value for troubletable.unitname
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk1
     *
     * @return the value of troubletable.risk1
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk1() {
        return risk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk1
     *
     * @param risk1 the value for troubletable.risk1
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk1(Integer risk1) {
        this.risk1 = risk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk2
     *
     * @return the value of troubletable.risk2
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk2() {
        return risk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk2
     *
     * @param risk2 the value for troubletable.risk2
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk2(Integer risk2) {
        this.risk2 = risk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk3
     *
     * @return the value of troubletable.risk3
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk3() {
        return risk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk3
     *
     * @param risk3 the value for troubletable.risk3
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk3(Integer risk3) {
        this.risk3 = risk3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk4
     *
     * @return the value of troubletable.risk4
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk4() {
        return risk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk4
     *
     * @param risk4 the value for troubletable.risk4
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk4(Integer risk4) {
        this.risk4 = risk4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk5
     *
     * @return the value of troubletable.risk5
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk5() {
        return risk5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk5
     *
     * @param risk5 the value for troubletable.risk5
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk5(Integer risk5) {
        this.risk5 = risk5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.risk6
     *
     * @return the value of troubletable.risk6
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getRisk6() {
        return risk6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.risk6
     *
     * @param risk6 the value for troubletable.risk6
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setRisk6(Integer risk6) {
        this.risk6 = risk6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troubletable.otherrisk
     *
     * @return the value of troubletable.otherrisk
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public Integer getOtherrisk() {
        return otherrisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troubletable.otherrisk
     *
     * @param otherrisk the value for troubletable.otherrisk
     *
     * @mbggenerated Sat Oct 08 15:37:59 CST 2016
     */
    public void setOtherrisk(Integer otherrisk) {
        this.otherrisk = otherrisk;
    }
}